<?php
 

/**
 * Implements hook_form_alter()
 */
function custom_user_form_alter(&$form, &$form_state, $form_id){
  
    switch($form_id){
       
        case 'user_register_form':
         $form['account']['name']['#access']=false;
         array_unshift($form['#validate'],'custom_user_register_validate');
        break;
    }
}  

/**
 * @param type $form
 * @param type $form_state
 * users to register and login using only an email address
 */

function custom_user_register_validate($form,&$form_state){
    if($form_state['values']['mail']){
       
       $form_state['values']['name']=$form_state['values']['mail'];
   }
  
}
